---
- name: Copy dockerfile
  ansible.builtin.copy:
    src: files/dockerfile
    dest: /tmp/Dockerfile
    mode: "0644"
  register: dockerfile_copy

- name: Create backup script
  become: true
  ansible.builtin.copy:
    src: "files/backup.sh"
    dest: "/tmp/backup.sh"
    mode: "0644"
  register: backup_script_copy

- name: Build Docker image
  become: true
  community.docker.docker_image:
    name: "{{ backup_image_name }}"
    tag: "{{ backup_image_tag }}"
    source: build
    push: false
    build:
      path: /tmp
    force_source: "{{ dockerfile_copy.changed or backup_script_copy.changed }}"
    state: present
  notify: "Restart {{ service_name }}"

- name: Create backup .env file
  become: true
  ansible.builtin.template:
    src: templates/docker-compose/backup-toolkit.env.j2
    dest: "{{ service_config_dir }}/backup-toolkit.env"
    group: "{{ service_user }}"
    owner: "{{ service_user }}"
    mode: "0400"
  notify: "Restart {{ service_name }}"

- name: Create backup systemd service file
  become: true
  ansible.builtin.template:
    src: "templates/backup/backup.service.j2"
    dest: /etc/systemd/system/{{ service_name }}-backup.service
    owner: root
    group: root
    mode: "0644"
  register: service_file_uptime_kuma_backup

- name: Create backup systemd timer file
  become: true
  ansible.builtin.template:
    src: "templates/backup/backup.timer.j2"
    dest: /etc/systemd/system/{{ service_name }}-backup.timer
    owner: root
    group: root
    mode: "0644"
  vars:
    service: "{{ service_name }}"
    cron: "*-*-* 04:00:00"
  register: timer_file_uptime_kuma_backup

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: timer_file_uptime_kuma_backup.changed or service_file_uptime_kuma_backup.changed

- name: Enable and start backup timer
  become: true
  ansible.builtin.systemd:
    name: "{{ service_name }}-backup.timer"
    enabled: true
    state: started
  when: timer_file_uptime_kuma_backup.changed or service_file_uptime_kuma_backup.changed
