- name: Create docker compose config
  become: true
  ansible.builtin.template:
    src: "templates/docker-compose/docker-compose.yml.j2"
    dest: "{{ service_config_dir }}/docker-compose.yml"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: "0644"
  notify: "Restart {{ service_name }}"

- name: Create systemd service file
  become: true
  ansible.builtin.template:
    src: "templates/uptime-kuma/{{ service_name }}.service.j2"
    dest: /etc/systemd/system/{{ service_name }}.service
    owner: root
    group: root
    mode: "0644"
  notify: "Restart {{ service_name }}"
